backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'phones'
    label: 'Phones'
    folder: 'src/pages/phones'
    create: true
    identifier_field: name
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "phone-page"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Phone Image", name: "phoneImage", widget: image}
      - {label: "Brand", name: "brand", widget: "string"}
      - {label: "RAM", name: "RAM", widget: "string"}
